services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 123
       POSTGRES_DB: nest
    networks:
      - asia22
  test-db:
    image: postgres:17
    ports:
      - 5435:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 123
       POSTGRES_DB: nest
    networks:
      - asia22

networks:
  asia22: